---
abstract: 'Turns a long list into an easy-to-navigate tree'
author:
  - 'Peter Corlett <abuse@cabal.org.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-DrillDown
requires:
  Carp: 0
  Moose: 0
  MooseX::Types::Moose: 0
  perl: 5.006
version: 0.005
